### ISSUE TITLE
Access Firebase Storage instance

### ISSUE THREAD

**Issue by sacredvoid** [khaosdoctor/multer-firebase-storage#16]
Hey, great library, just had a quick doubt. How should I go about accessing the firebase storage instance (that we get when we init firebase the vanilla way), I need to delete files and have that `getStorage()` reference to create a file ref object that will then be passed to firebase's deleteObject method. Any help appreciated!

**Comment by khaosdoctor** [comment]
Hey! I'm not sure what you want to do but you can provide your own firebase instance too, so you can have it accessible everywhere https://github.com/khaosdoctor/multer-firebase-storage#using-your-own-firebase-instance

**Comment by sacredvoid** [comment]
Correct me if I am wrong, but the FirebaseStorage object that is created by this package, cannot be referenced outside of it, and I'll need to have another instance of FirebaseStorage to further manipulate the blobs that are on the cloud ie. delete/edit the metadata. @khaosdoctor

**Comment by khaosdoctor** [comment]
No actually if you pass your own instance of the Firebase object, the lib will use it instead of creating a new one, so you can actually reuse it outside the scope

**Comment by sacredvoid** [comment]
Hey, thanks for the reply, I tried using the code provided to init firebase app. I'm trying to use this in a different file, but I get an error like [this](https://stackoverflow.com/questions/69880872/firebase-getauth-throws-error-getprovider-of-undefined-but-can-access-database) but for `getStorage`. Been stuck on this for quite some time now, any help is appreciated

**Comment by sacredvoid** [comment]
Here's how I did it for anyone stuck on this: 
```
import { getStorage } from "firebase-admin/storage"

const deleteFile = (req, res) => {
    const fileLink = req.body.public_url;
    const fileName = extractFileName(fileLink);
    const fbStorage = getStorage();
    const fileRef = fbStorage.bucket().file(folderName+fileName);
    fileRef
       .delete()
       .then(() => {
        res.sendStatus(200);
       })
        .catch(err => {
           console.error(`Failed to delete file`, err);
           res.sendStatus(404);
        });
}
```

Thanks for your help and this awesome package @khaosdoctor
