### ISSUE TITLE
jsonwebtoken unrestricted key type could lead to legacy keys usage

### ISSUE THREAD

**Issue by dahl898** [khaosdoctor/multer-firebase-storage#8]
Hey, yesterday npm started to yell at me when I was trying to install the package. There is some issue with the older versions of jsonwebtoken (screenshot from npm audit is attached).  I'm very new to web development and programming in general, so I decided to report it as an issue because it just doesn't seem like a safe solution to me to try to update the jsonwebtoken directly in the multer-firebase-storage folder.

![image](https://user-images.githubusercontent.com/80483526/209400623-09cb59f5-5640-430f-a1ae-7aabce9f770e.png)

**Comment by khaosdoctor** [comment]
You are completely correct, I'll update the package versions that this repository relies on and generate a new safe version! Thanks for commenting!

**Comment by dahl898** [comment]
Thanks! Great package btw, helped me a lot.
